/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChildrenComponent {}
  interface MyComponent {}
}

declare global {


  interface HTMLChildrenComponentElement extends Components.ChildrenComponent, HTMLStencilElement {}
  var HTMLChildrenComponentElement: {
    prototype: HTMLChildrenComponentElement;
    new (): HTMLChildrenComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'children-component': HTMLChildrenComponentElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface ChildrenComponent {
    'onTodoCompleted'?: (event: CustomEvent<any>) => void;
  }
  interface MyComponent {}

  interface IntrinsicElements {
    'children-component': ChildrenComponent;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'children-component': LocalJSX.ChildrenComponent & JSXBase.HTMLAttributes<HTMLChildrenComponentElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


